language: erlang
install: true
before_script:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod a+x rebar3
env:
  - PATH="$TRAVIS_BUILD_DIR:$PATH"
script: make travis_ci
notifications:
  email: eric@ericb.me
otp_release:
  - 18.2
  - 17.0
  - R16B02
